# Generated by Django 5.0 on 2024-01-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_question', models.CharField(max_length=255)),
                ('assignment_description', models.TextField()),
                ('assignment_requirements', models.TextField()),
                ('assignment_banner', models.ImageField(blank=True, null=True, upload_to='assignment_banners/')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
                ('referral_link1', models.URLField(max_length=255)),
                ('referral_link2', models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='student',
            name='level_student',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment1', to='accounts.assignment'),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment2', to='accounts.assignment'),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment3', to='accounts.assignment'),
        ),
    ]
