# Generated by Django 5.0 on 2024-03-30 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assignment_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0),
        ),
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment1_github_Link', models.TextField(blank=True, null=True)),
                ('Assignment1_linkedin_link', models.TextField(blank=True, null=True)),
                ('Assignment2_github_Link', models.TextField(blank=True, null=True)),
                ('Assignment2_linkedin_link', models.TextField(blank=True, null=True)),
                ('Assignment3_github_Link', models.TextField(blank=True, null=True)),
                ('Assignment3_linkedin_link', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
