# Generated by Django 5.0 on 2024-03-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_assignment_level_assignmentsubmit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmit',
            old_name='domain',
            new_name='student',
        ),
    ]
