# Generated by Django 5.0 on 2024-04-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_domain_assignmentsubmit_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_banner1',
            field=models.ImageField(blank=True, null=True, upload_to='assignment_banners1/'),
        ),
    ]
