# Generated by Django 5.0 on 2024-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_assignmentsubmit_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level_student',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'pending'), (5, 'Certificate Level')], default=0),
        ),
    ]
