# Generated by Django 5.0.4 on 2024-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_student_level_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
