# Generated by Django 5.0 on 2024-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_assignment1status_student_assignment2status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignment1endttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment1rejectioncount',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment1starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment2endttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment2rejectioncount',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment2starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment3endttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment3rejectioncount',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment3starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
