# Generated by Django 4.0 on 2024-08-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_student_assignment1rejectioncount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='referral_link1',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='referral_link2',
        ),
        migrations.AddField(
            model_name='assignment',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.RefralLink'),
        ),
    ]
