# Generated by Django 4.0 on 2024-08-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_refrallink_remove_assignment_referral_link1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
