# Generated by Django 5.0 on 2024-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_assignment_youtube_video_id'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='mentor',
            field=models.ManyToManyField(blank=True, null=True, to='mentor.mentor'),
        ),
    ]
