# Generated by Django 5.0 on 2024-08-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_domain_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='mentor',
        ),
    ]
